extends Node

class Lanague:
	pass

class ZH extends Lanague:
	static var SETTING 								: String = "设置"
	static var WORK_SPACE 							: String = "工作路径"
	static var CLEAR_LOG 							: String  = "清除日志"
	static var EXIT 									: String  = "退出"
	static var MODEL 								: String  = "模块"
	static var ANDROID_SCRIPT 						: String  = "安卓脚本"
	static var FILE_SCRIPT 							: String  = "文件脚本"
	static var ABOUT 								: String  = "关于"
	static var SOFTWARE_VERSION 						: String  = "软件版本"
	static var HELP_DOCUMENTATION 					: String  = "帮助文档"
	static var CONTACT_THE_AUTHOR 					: String  = "联系作者"
	static var CURRENT_WORK_SPACE 					: String  = "当前工作路径 "
	static var THE_PATH_CANNOT_BE_EMPTY 				: String  = "路径不能为空 "
	static var THE_PREFIX_CANNOT_BE_EMPTY 			: String  = "前缀不能为空 "
	static var BATCH_RENAME 							: String  = "进行批量重命名 "
	static var THE_PREFIX_FOR_RENAMING_IS				: String  = "重命名的前缀是:"
	static var THE_NUMBER_OF_DIGITS_FOR_RENAMING		: String  = "重命名的位数是:"
	static var NAMING_PREFIX_CANNOT_BE_EMPTY			: String  = "命名前缀不能为空"
	static var NAME_PREFIX_OF_INPUT_FILE				: String  = "输入文件的命名前缀"
	static var NAMING_DIGITS_CAN_ONLY_BE_NUMBERS		: String  = "命名位数只能是 1-9 的数字"
	static var INPUT_FILE_NAMING_LENGTH				: String  = "输入文件的命名位数"
	static var RENAME_SETTING						: String  = "重命名设置"
	static var RENAME_STARTS							: String  = "重命名开始"
	static var ALL_COMPRESSED						: String  = "全部压缩"
	static var UNZIP_ALL								: String  = "全部解压"
	static var FIND_FILES							: String  = "查找文件"
	static var CONFIRM								: String  = "确认"
	static var CANCEL								: String  = "取消"
	static var ARE_YOU_SURE_YOU_WANT_TO_EXIT			: String  = "您确认退出吗？"
	static var FILE_RENAMING_OPTION_SETTINGS			: String  = "文件 重命名 选项设置"
	static var ENTER_THE_PREFIX_TO_RENAME				: String  = "输入重命名的前缀"
	static var ENTER_THE_NUMBER_OF_BITS_TO_RENAME		: String  = "输入重命名的位数"
	pass

class EN extends Lanague:
	static var SETTING 								: String = "setting"
	static var WORK_SPACE 							: String = "work space"
	static var CLEAR_LOG 							: String  = "clear log"
	static var EXIT 									: String  = "exit"
	static var MODEL 								: String  = "model"
	static var ANDROID_SCRIPT 						: String  = "android script"
	static var FILE_SCRIPT 							: String  = "file script"
	static var ABOUT 								: String  = "about"
	static var SOFTWARE_VERSION 						: String  = "software version"
	static var HELP_DOCUMENTATION 					: String  = "help documentation"
	static var CONTACT_THE_AUTHOR 					: String  = "contact the_author"
	static var CURRENT_WORK_SPACE 					: String  = "current work_space "
	static var THE_PATH_CANNOT_BE_EMPTY				: String  = "The path cannot be empty "
	static var THE_PREFIX_CANNOT_BE_EMPTY 			: String  = "The prefix cannot be empty "
	static var BATCH_RENAME							: String  = "Batch rename "
	static var THE_PREFIX_FOR_RENAMING_IS				: String  = "The prefix for renaming is:"
	static var THE_NUMBER_OF_DIGITS_FOR_RENAMING		: String  = "The number of digits for renaming is:"
	static var NAMING_PREFIX_CANNOT_BE_EMPTY			: String  = "Naming prefix cannot be empty"
	static var NAME_PREFIX_OF_INPUT_FILE				: String  = "Name prefix of input file"
	static var NAMING_DIGITS_CAN_ONLY_BE_NUMBERS		: String  = "Naming digits can only be numbers from 1 to 9"
	static var INPUT_FILE_NAMING_LENGTH				: String  = "Input file naming length"
	static var RENAME_SETTING						: String  = "rename setting"
	static var RENAME_STARTS							: String  = "rename starts"
	static var ALL_COMPRESSED						: String  = "all compressed"
	static var UNZIP_ALL								: String  = "unzip all"
	static var FIND_FILES							: String  = "find files"
	static var CONFIRM								: String  = "confirm"
	static var CANCEL								: String  = "cancel"
	static var ARE_YOU_SURE_YOU_WANT_TO_EXIT			: String  = "Are you sure you want to exit?"
	static var FILE_RENAMING_OPTION_SETTINGS			: String  = "File renaming option settings"
	static var ENTER_THE_PREFIX_TO_RENAME				: String  = "Enter the prefix to rename"
	static var ENTER_THE_NUMBER_OF_BITS_TO_RENAME		: String  = "Enter the number of bits to rename"
	pass
